### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by micnekr** [micnekr/chat#4]
- [ ] login rememberMe redirect check on server
- [ ] cluster and solve memory problems
- [ ] tests
- [ ] end to end encryption
- [ ] tags for messages
- [ ] photos, videos
- [ ] submit a bug page
- [ ] fix protocol
- [ ] fix signup, sql/create chat to use transactions
- [ ] ratelimit messages
- [ ] test if it is faster to send all messages or n last messages
- [ ] add a button "show more messages"
- [ ] change data format for getChatAndUserData
- [ ] add messages about joining and leaving the chat
- [ ] cache
- [ ] user profiles
- [ ] user icons
- [ ] change all boolean queries to be sql and merge into transaction with other statements if possible
- [ ] change password
- [ ] look at security and node practices
- [ ] optimise psql get
- [ ] user profiles in the menu
- [X] use hbs to choose between buttons in chatinfo and optimise further
- [ ] check time of request processing
- [X] use queries, not cookies
- [ ] change menu to post and check for errors

!!!!!!!!!!!!!!!IMPORTANT!!!!!!!!!!!!!!!!!!!!!!!!
- [X] move xss protection to client side
- [X] xss in search terms
- [ ] serverside xss
- [x] disable suggestions in chat textarea
- [x] log errors not caught by express
- [x] ufw enable
- [x] signup search for names which are used
- [x] app.set trust proxy 1
- [x] httponly for cookies
- [x] long term login ratelimit
- [x] snyk

- [ ] LOOK AT RELEASE TODOS
